# Application Configuration
url=http://ccst-testvm.pune.cdac.in:8080/epAdmin/index.jsp

# Browser Configuration (chrome / firefox/edge)
browser=chrome

# Wait Configuration in second 
timeout=10





#Dummy data 

coordinatorUserId=1138
coordinatorPassword=cdac1234

adminUserId=1002
adminPassword=eParikshaAdmin#123

studentUserId=1234567014
studentPassword=7014

